# Generated by Django 5.0.3 on 2024-04-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_borrow_balance_after_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
